sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - git clone git://github.com/openmicroscopy/omero-test-infra .omero

script:
  - .omero/docker app

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
